"""updt user col type

Revision ID: ed6c32a47800
Revises: 51af22eb3a64
Create Date: 2025-02-02 12:52:43.272649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6c32a47800'
down_revision: Union[str, None] = '51af22eb3a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'user',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'user',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
